[tool.poetry]
name = "presidio-research"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
jupyterlab = "^2.2.4"
spacy = "^2.3.2"
requests = "2.22.0"
pandas = "^1.1.0"
tqdm = "^4.48.2"
haikunator = "^2.1.0"
schwifty = "^2020.8.0"
faker = "^4.1.1"
regex = "^2020.7.14"
sklearn_crfsuite = "^0.3.6"
pytest = "^6.0.1"
matplotlib = "^3.3.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
mypy = "^0.782"
yapf = "^0.30.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
